title: Loh Qian Kai # your name (or website title) here
logo: "/images/lohqiankai.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently studying Year 3 Computer Science with AI in University of Nottingham. Will be graduate in summer 2022 and looking for a job after that. My hobbies are cooking, problem solving and badminton.
  <br><br>
  I was a chess player and passionate about Mathematics. I was inspired by AlphaZero to study in this field. Currently interested in AI and Robotics especially Reinforcement Learning.
  <br><br>
  <a href="https://www.linkedin.com/in/qian-kai-loh-a117681a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
