title: Loh Qian Kai # your name (or website title) here
logo: "/images/lohqiankai.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I was a chess player and passionate about Mathematics. Currently interested in AI and Robotics especially Reinforcement Learning.
  <br><br>
  Teset
  <br><br>
  <a href="https://www.linkedin.com/in/qian-kai-loh-a117681a4/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
